### ISSUE TITLE
What does the subprocess in the preprocess.py do?

### ISSUE THREAD

**Issue by oo7ww** [asmiller1989/Ethereum_Blockchain_Parser#8]
`subprocess.call([
    "(geth --rpc --rpcport 8545 > {}/geth.log 2>&1) &".format(LOGDIR),
    "(mongod --dbpath mongo/data --port 27017 > {}/mongo.log 2>&1) &".format(LOGDIR)
], shell=True)`

Hello, I'm trying to parse blockchain data to MongoDB by this project.
I have finished the geth fast sync and got stuck in the preprocessing step.
What's the meaning of the command and where is the geth.log?

**Comment by AndriyYakymiv** [comment]
This command starts a subprocess  which runs `geth `node as a service. To get **geth.log** file you need to create a folder _logs_ inside Preprocessing folder. When you will run **preprocess.py** it will list you logs inside **geth.log** file.

**Comment by oo7ww** [comment]
I have turned to use web3.py to get query the geth to get the block data.
But, still thank you for your explain, AndriyYakymiv.
